### PR TITLE
Zipf distribution unit test

### PR DESCRIPTION
**Pull request by linas**
This pull req provides an extensive unit test. Things work, it passes, there's a bit of cleanup left.

The original implementation was deeply, fundamentally broken. The revised implementation works.

The original implementation was a transcription of some C++ code, which transcribed some (decade old) java code, which was insane. Whoever wrote the java code fundamentally broke everything, didn't unit test, and it got copied all over the interwebs. I made the mistake of copying it.

The original paper describes the correct algo; it is readily available here: https://www.researchgate.net/publication/220136322_Rejection-Inversion_to_Generate_Variates_from_Monotone_Discrete_Distributions It was posted by one of the original authors.

I implemented the algo from the original paper in `zipf-zri.scm` . It works great! The unit test confirms this.

It has one minor wart, it blows up for the parameter value of s=1 (which the original authors noted). I think this is fixable, will try to fix.

### CODE REVIEW

**Comment by linas** [comment]
Attention!! I have to retract some of the commentary above! The original algorithm "ZRI" from the original paper does work correctly!  I was using a non-zero value for the "Hurwicz zeta" parameter, which messed things up. Please apply this pull req .. or wait a bit longer and I'll push additional changes to get the unit test going.

The non-zri implementation remains broken, and the root cause of that failure remains unclear. I'll give it one more try tomorrow.

**Comment by linas** [comment]
Update: The original algorithm as described by the original authors, works great and passes extensive unit tests. The work here is "almost" done; there's some assorted cleanup I want to do.

**Comment by arthurgleckler** [comment]
Great work!  I'm going to wait to merge this until you let me know that you're done.

**Comment by linas** [comment]
@arthurgleckler   I believe I am done with this pull req (documentation to come next)

The implementation looks good, the unit tests pass. I believe I've done the integration correctly, but you should check.  I work in guile, and so may have inadvertently left a few guile-isms in the code. One in particular is the use of `inexact->exact` which I just use without calling out srfi-70 to get this. There might be others.

**Comment by linas** [comment]
Oh, not quite done: one last little tweak: provide default values for the trailing two parameters, so that they become optional. Just a moment...

**Comment by linas** [comment]
... done.

**Pull request merged**
